// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// test.cpp
void dummy();
extern "C" SEXP _cpp20_dummy() {
  BEGIN_CPP11
    dummy();
    return R_NilValue;
  END_CPP11
}
// test.cpp
void cpp_set_threads(int n);
extern "C" SEXP _cpp20_cpp_set_threads(SEXP n) {
  BEGIN_CPP11
    cpp_set_threads(cpp11::as_cpp<cpp11::decay_t<int>>(n));
    return R_NilValue;
  END_CPP11
}
// test.cpp
SEXP foo(SEXP x);
extern "C" SEXP _cpp20_foo(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP bar(SEXP x);
extern "C" SEXP _cpp20_bar(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(bar(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foobar(SEXP x);
extern "C" SEXP _cpp20_foobar(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foobar(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foofoo();
extern "C" SEXP _cpp20_foofoo() {
  BEGIN_CPP11
    return cpp11::as_sexp(foofoo());
  END_CPP11
}
// test.cpp
SEXP foo6(SEXP x);
extern "C" SEXP _cpp20_foo6(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo6(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo7(SEXP x);
extern "C" SEXP _cpp20_foo7(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo7(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo9();
extern "C" SEXP _cpp20_foo9() {
  BEGIN_CPP11
    return cpp11::as_sexp(foo9());
  END_CPP11
}
// test.cpp
SEXP foo_attrs(SEXP x);
extern "C" SEXP _cpp20_foo_attrs(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_attrs(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo12(SEXP x, SEXP attrs);
extern "C" SEXP _cpp20_foo12(SEXP x, SEXP attrs) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo12(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x), cpp11::as_cpp<cpp11::decay_t<SEXP>>(attrs)));
  END_CPP11
}
// test.cpp
SEXP foo14();
extern "C" SEXP _cpp20_foo14() {
  BEGIN_CPP11
    return cpp11::as_sexp(foo14());
  END_CPP11
}
// test.cpp
SEXP foo26();
extern "C" SEXP _cpp20_foo26() {
  BEGIN_CPP11
    return cpp11::as_sexp(foo26());
  END_CPP11
}
// test.cpp
SEXP foo27(SEXP cols);
extern "C" SEXP _cpp20_foo27(SEXP cols) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo27(cpp11::as_cpp<cpp11::decay_t<SEXP>>(cols)));
  END_CPP11
}
// test.cpp
SEXP foo28a(SEXP x, SEXP y);
extern "C" SEXP _cpp20_foo28a(SEXP x, SEXP y) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo28a(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x), cpp11::as_cpp<cpp11::decay_t<SEXP>>(y)));
  END_CPP11
}
// test.cpp
SEXP foo28b(SEXP x, SEXP y);
extern "C" SEXP _cpp20_foo28b(SEXP x, SEXP y) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo28b(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x), cpp11::as_cpp<cpp11::decay_t<SEXP>>(y)));
  END_CPP11
}
// test.cpp
int foo30();
extern "C" SEXP _cpp20_foo30() {
  BEGIN_CPP11
    return cpp11::as_sexp(foo30());
  END_CPP11
}
// test.cpp
SEXP foo_rep_len(SEXP x, int n);
extern "C" SEXP _cpp20_foo_rep_len(SEXP x, SEXP n) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_rep_len(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x), cpp11::as_cpp<cpp11::decay_t<int>>(n)));
  END_CPP11
}
// test.cpp
SEXP foo_sum(SEXP x, bool na_rm);
extern "C" SEXP _cpp20_foo_sum(SEXP x, SEXP na_rm) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_sum(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x), cpp11::as_cpp<cpp11::decay_t<bool>>(na_rm)));
  END_CPP11
}
// test.cpp
SEXP foo_mean(SEXP x, bool na_rm);
extern "C" SEXP _cpp20_foo_mean(SEXP x, SEXP na_rm) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_mean(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x), cpp11::as_cpp<cpp11::decay_t<bool>>(na_rm)));
  END_CPP11
}
// test.cpp
SEXP foo_var(SEXP x, bool na_rm);
extern "C" SEXP _cpp20_foo_var(SEXP x, SEXP na_rm) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_var(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x), cpp11::as_cpp<cpp11::decay_t<bool>>(na_rm)));
  END_CPP11
}
// test.cpp
SEXP foo_sum_int(SEXP x, bool na_rm);
extern "C" SEXP _cpp20_foo_sum_int(SEXP x, SEXP na_rm) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_sum_int(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x), cpp11::as_cpp<cpp11::decay_t<bool>>(na_rm)));
  END_CPP11
}
// test.cpp
SEXP foo_range(SEXP x, bool na_rm);
extern "C" SEXP _cpp20_foo_range(SEXP x, SEXP na_rm) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_range(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x), cpp11::as_cpp<cpp11::decay_t<bool>>(na_rm)));
  END_CPP11
}
// test.cpp
SEXP foo_na_count(SEXP x);
extern "C" SEXP _cpp20_foo_na_count(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_na_count(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo_is_na(SEXP x);
extern "C" SEXP _cpp20_foo_is_na(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_is_na(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo39(SEXP x, bool na_rm);
extern "C" SEXP _cpp20_foo39(SEXP x, SEXP na_rm) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo39(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x), cpp11::as_cpp<cpp11::decay_t<bool>>(na_rm)));
  END_CPP11
}
// test.cpp
SEXP foo40(SEXP x, bool na_rm);
extern "C" SEXP _cpp20_foo40(SEXP x, SEXP na_rm) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo40(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x), cpp11::as_cpp<cpp11::decay_t<bool>>(na_rm)));
  END_CPP11
}
// test.cpp
SEXP foo41(SEXP x);
extern "C" SEXP _cpp20_foo41(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo41(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo42(SEXP x);
extern "C" SEXP _cpp20_foo42(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo42(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo43(SEXP x);
extern "C" SEXP _cpp20_foo43(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo43(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo44(SEXP x);
extern "C" SEXP _cpp20_foo44(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo44(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo48(SEXP x);
extern "C" SEXP _cpp20_foo48(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo48(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo49(SEXP x, bool na_rm);
extern "C" SEXP _cpp20_foo49(SEXP x, SEXP na_rm) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo49(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x), cpp11::as_cpp<cpp11::decay_t<bool>>(na_rm)));
  END_CPP11
}
// test.cpp
SEXP foo50(SEXP x, bool na_rm);
extern "C" SEXP _cpp20_foo50(SEXP x, SEXP na_rm) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo50(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x), cpp11::as_cpp<cpp11::decay_t<bool>>(na_rm)));
  END_CPP11
}
// test.cpp
SEXP foo51(SEXP x);
extern "C" SEXP _cpp20_foo51(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo51(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo54(SEXP x);
extern "C" SEXP _cpp20_foo54(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo54(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo_add1(SEXP x, SEXP y);
extern "C" SEXP _cpp20_foo_add1(SEXP x, SEXP y) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_add1(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x), cpp11::as_cpp<cpp11::decay_t<SEXP>>(y)));
  END_CPP11
}
// test.cpp
SEXP foo_add(SEXP x);
extern "C" SEXP _cpp20_foo_add(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_add(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo_vec_add(SEXP x, SEXP y);
extern "C" SEXP _cpp20_foo_vec_add(SEXP x, SEXP y) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_vec_add(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x), cpp11::as_cpp<cpp11::decay_t<SEXP>>(y)));
  END_CPP11
}
// test.cpp
SEXP foo_vec_subtract(SEXP x, SEXP y);
extern "C" SEXP _cpp20_foo_vec_subtract(SEXP x, SEXP y) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_vec_subtract(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x), cpp11::as_cpp<cpp11::decay_t<SEXP>>(y)));
  END_CPP11
}
// test.cpp
SEXP foo_vec_multiply(SEXP x, SEXP y);
extern "C" SEXP _cpp20_foo_vec_multiply(SEXP x, SEXP y) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_vec_multiply(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x), cpp11::as_cpp<cpp11::decay_t<SEXP>>(y)));
  END_CPP11
}
// test.cpp
SEXP foo_vec_divide(SEXP x, SEXP y);
extern "C" SEXP _cpp20_foo_vec_divide(SEXP x, SEXP y) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_vec_divide(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x), cpp11::as_cpp<cpp11::decay_t<SEXP>>(y)));
  END_CPP11
}
// test.cpp
SEXP foo_factor(SEXP x);
extern "C" SEXP _cpp20_foo_factor(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_factor(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo_factor2(SEXP x, SEXP levels);
extern "C" SEXP _cpp20_foo_factor2(SEXP x, SEXP levels) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_factor2(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x), cpp11::as_cpp<cpp11::decay_t<SEXP>>(levels)));
  END_CPP11
}
// test.cpp
SEXP foo_gcd(SEXP x, bool na_rm);
extern "C" SEXP _cpp20_foo_gcd(SEXP x, SEXP na_rm) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_gcd(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x), cpp11::as_cpp<cpp11::decay_t<bool>>(na_rm)));
  END_CPP11
}
// test.cpp
SEXP foo_lcm(SEXP x, bool na_rm);
extern "C" SEXP _cpp20_foo_lcm(SEXP x, SEXP na_rm) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_lcm(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x), cpp11::as_cpp<cpp11::decay_t<bool>>(na_rm)));
  END_CPP11
}
// test.cpp
SEXP foo_sset(SEXP x, SEXP i);
extern "C" SEXP _cpp20_foo_sset(SEXP x, SEXP i) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_sset(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x), cpp11::as_cpp<cpp11::decay_t<SEXP>>(i)));
  END_CPP11
}
// test.cpp
SEXP foo_lgl();
extern "C" SEXP _cpp20_foo_lgl() {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_lgl());
  END_CPP11
}
// test.cpp
SEXP foo_unique(SEXP x);
extern "C" SEXP _cpp20_foo_unique(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_unique(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo_sorted_unique(SEXP x);
extern "C" SEXP _cpp20_foo_sorted_unique(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_sorted_unique(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo_as_str(SEXP x);
extern "C" SEXP _cpp20_foo_as_str(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_as_str(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo_match(SEXP x, SEXP table);
extern "C" SEXP _cpp20_foo_match(SEXP x, SEXP table) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_match(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x), cpp11::as_cpp<cpp11::decay_t<SEXP>>(table)));
  END_CPP11
}
// test.cpp
SEXP foo_all_whole(SEXP x);
extern "C" SEXP _cpp20_foo_all_whole(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_all_whole(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo_copy(SEXP x);
extern "C" SEXP _cpp20_foo_copy(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_copy(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo_group_id(SEXP x);
extern "C" SEXP _cpp20_foo_group_id(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_group_id(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo_n_groups(SEXP x);
extern "C" SEXP _cpp20_foo_n_groups(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_n_groups(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo_groups_sorted(SEXP x);
extern "C" SEXP _cpp20_foo_groups_sorted(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_groups_sorted(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo_group_starts(SEXP x, int n_groups, bool sorted);
extern "C" SEXP _cpp20_foo_group_starts(SEXP x, SEXP n_groups, SEXP sorted) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_group_starts(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x), cpp11::as_cpp<cpp11::decay_t<int>>(n_groups), cpp11::as_cpp<cpp11::decay_t<bool>>(sorted)));
  END_CPP11
}
// test.cpp
SEXP foo_remainder();
extern "C" SEXP _cpp20_foo_remainder() {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_remainder());
  END_CPP11
}
// test.cpp
SEXP foo_between(SEXP x, SEXP lo, SEXP hi);
extern "C" SEXP _cpp20_foo_between(SEXP x, SEXP lo, SEXP hi) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_between(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x), cpp11::as_cpp<cpp11::decay_t<SEXP>>(lo), cpp11::as_cpp<cpp11::decay_t<SEXP>>(hi)));
  END_CPP11
}
// test.cpp
SEXP foo_make_vec_test();
extern "C" SEXP _cpp20_foo_make_vec_test() {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_make_vec_test());
  END_CPP11
}
// test.cpp
SEXP foofoofoo();
extern "C" SEXP _cpp20_foofoofoo() {
  BEGIN_CPP11
    return cpp11::as_sexp(foofoofoo());
  END_CPP11
}
// test.cpp
SEXP foo_which(SEXP x);
extern "C" SEXP _cpp20_foo_which(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_which(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo_which_inverted(SEXP x);
extern "C" SEXP _cpp20_foo_which_inverted(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_which_inverted(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo_asint64(SEXP x);
extern "C" SEXP _cpp20_foo_asint64(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_asint64(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo_order(SEXP x);
extern "C" SEXP _cpp20_foo_order(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_order(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo_stable_order(SEXP x);
extern "C" SEXP _cpp20_foo_stable_order(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_stable_order(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo_group_id2(SEXP x);
extern "C" SEXP _cpp20_foo_group_id2(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_group_id2(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo_sorted(SEXP x);
extern "C" SEXP _cpp20_foo_sorted(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_sorted(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
void test1();
extern "C" SEXP _cpp20_test1() {
  BEGIN_CPP11
    test1();
    return R_NilValue;
  END_CPP11
}
// test.cpp
SEXP foo_str_vectors(SEXP x);
extern "C" SEXP _cpp20_foo_str_vectors(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_str_vectors(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// test.cpp
SEXP foo_seqs(SEXP sizes, SEXP from, SEXP by);
extern "C" SEXP _cpp20_foo_seqs(SEXP sizes, SEXP from, SEXP by) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_seqs(cpp11::as_cpp<cpp11::decay_t<SEXP>>(sizes), cpp11::as_cpp<cpp11::decay_t<SEXP>>(from), cpp11::as_cpp<cpp11::decay_t<SEXP>>(by)));
  END_CPP11
}
// test.cpp
SEXP foo_seqs2(SEXP sizes, SEXP from, SEXP by);
extern "C" SEXP _cpp20_foo_seqs2(SEXP sizes, SEXP from, SEXP by) {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_seqs2(cpp11::as_cpp<cpp11::decay_t<SEXP>>(sizes), cpp11::as_cpp<cpp11::decay_t<SEXP>>(from), cpp11::as_cpp<cpp11::decay_t<SEXP>>(by)));
  END_CPP11
}
// test.cpp
SEXP foo_test();
extern "C" SEXP _cpp20_foo_test() {
  BEGIN_CPP11
    return cpp11::as_sexp(foo_test());
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cpp20_bar",                (DL_FUNC) &_cpp20_bar,                1},
    {"_cpp20_cpp_set_threads",    (DL_FUNC) &_cpp20_cpp_set_threads,    1},
    {"_cpp20_dummy",              (DL_FUNC) &_cpp20_dummy,              0},
    {"_cpp20_foo",                (DL_FUNC) &_cpp20_foo,                1},
    {"_cpp20_foo12",              (DL_FUNC) &_cpp20_foo12,              2},
    {"_cpp20_foo14",              (DL_FUNC) &_cpp20_foo14,              0},
    {"_cpp20_foo26",              (DL_FUNC) &_cpp20_foo26,              0},
    {"_cpp20_foo27",              (DL_FUNC) &_cpp20_foo27,              1},
    {"_cpp20_foo28a",             (DL_FUNC) &_cpp20_foo28a,             2},
    {"_cpp20_foo28b",             (DL_FUNC) &_cpp20_foo28b,             2},
    {"_cpp20_foo30",              (DL_FUNC) &_cpp20_foo30,              0},
    {"_cpp20_foo39",              (DL_FUNC) &_cpp20_foo39,              2},
    {"_cpp20_foo40",              (DL_FUNC) &_cpp20_foo40,              2},
    {"_cpp20_foo41",              (DL_FUNC) &_cpp20_foo41,              1},
    {"_cpp20_foo42",              (DL_FUNC) &_cpp20_foo42,              1},
    {"_cpp20_foo43",              (DL_FUNC) &_cpp20_foo43,              1},
    {"_cpp20_foo44",              (DL_FUNC) &_cpp20_foo44,              1},
    {"_cpp20_foo48",              (DL_FUNC) &_cpp20_foo48,              1},
    {"_cpp20_foo49",              (DL_FUNC) &_cpp20_foo49,              2},
    {"_cpp20_foo50",              (DL_FUNC) &_cpp20_foo50,              2},
    {"_cpp20_foo51",              (DL_FUNC) &_cpp20_foo51,              1},
    {"_cpp20_foo54",              (DL_FUNC) &_cpp20_foo54,              1},
    {"_cpp20_foo6",               (DL_FUNC) &_cpp20_foo6,               1},
    {"_cpp20_foo7",               (DL_FUNC) &_cpp20_foo7,               1},
    {"_cpp20_foo9",               (DL_FUNC) &_cpp20_foo9,               0},
    {"_cpp20_foo_add",            (DL_FUNC) &_cpp20_foo_add,            1},
    {"_cpp20_foo_add1",           (DL_FUNC) &_cpp20_foo_add1,           2},
    {"_cpp20_foo_all_whole",      (DL_FUNC) &_cpp20_foo_all_whole,      1},
    {"_cpp20_foo_as_str",         (DL_FUNC) &_cpp20_foo_as_str,         1},
    {"_cpp20_foo_asint64",        (DL_FUNC) &_cpp20_foo_asint64,        1},
    {"_cpp20_foo_attrs",          (DL_FUNC) &_cpp20_foo_attrs,          1},
    {"_cpp20_foo_between",        (DL_FUNC) &_cpp20_foo_between,        3},
    {"_cpp20_foo_copy",           (DL_FUNC) &_cpp20_foo_copy,           1},
    {"_cpp20_foo_factor",         (DL_FUNC) &_cpp20_foo_factor,         1},
    {"_cpp20_foo_factor2",        (DL_FUNC) &_cpp20_foo_factor2,        2},
    {"_cpp20_foo_gcd",            (DL_FUNC) &_cpp20_foo_gcd,            2},
    {"_cpp20_foo_group_id",       (DL_FUNC) &_cpp20_foo_group_id,       1},
    {"_cpp20_foo_group_id2",      (DL_FUNC) &_cpp20_foo_group_id2,      1},
    {"_cpp20_foo_group_starts",   (DL_FUNC) &_cpp20_foo_group_starts,   3},
    {"_cpp20_foo_groups_sorted",  (DL_FUNC) &_cpp20_foo_groups_sorted,  1},
    {"_cpp20_foo_is_na",          (DL_FUNC) &_cpp20_foo_is_na,          1},
    {"_cpp20_foo_lcm",            (DL_FUNC) &_cpp20_foo_lcm,            2},
    {"_cpp20_foo_lgl",            (DL_FUNC) &_cpp20_foo_lgl,            0},
    {"_cpp20_foo_make_vec_test",  (DL_FUNC) &_cpp20_foo_make_vec_test,  0},
    {"_cpp20_foo_match",          (DL_FUNC) &_cpp20_foo_match,          2},
    {"_cpp20_foo_mean",           (DL_FUNC) &_cpp20_foo_mean,           2},
    {"_cpp20_foo_n_groups",       (DL_FUNC) &_cpp20_foo_n_groups,       1},
    {"_cpp20_foo_na_count",       (DL_FUNC) &_cpp20_foo_na_count,       1},
    {"_cpp20_foo_order",          (DL_FUNC) &_cpp20_foo_order,          1},
    {"_cpp20_foo_range",          (DL_FUNC) &_cpp20_foo_range,          2},
    {"_cpp20_foo_remainder",      (DL_FUNC) &_cpp20_foo_remainder,      0},
    {"_cpp20_foo_rep_len",        (DL_FUNC) &_cpp20_foo_rep_len,        2},
    {"_cpp20_foo_seqs",           (DL_FUNC) &_cpp20_foo_seqs,           3},
    {"_cpp20_foo_seqs2",          (DL_FUNC) &_cpp20_foo_seqs2,          3},
    {"_cpp20_foo_sorted",         (DL_FUNC) &_cpp20_foo_sorted,         1},
    {"_cpp20_foo_sorted_unique",  (DL_FUNC) &_cpp20_foo_sorted_unique,  1},
    {"_cpp20_foo_sset",           (DL_FUNC) &_cpp20_foo_sset,           2},
    {"_cpp20_foo_stable_order",   (DL_FUNC) &_cpp20_foo_stable_order,   1},
    {"_cpp20_foo_str_vectors",    (DL_FUNC) &_cpp20_foo_str_vectors,    1},
    {"_cpp20_foo_sum",            (DL_FUNC) &_cpp20_foo_sum,            2},
    {"_cpp20_foo_sum_int",        (DL_FUNC) &_cpp20_foo_sum_int,        2},
    {"_cpp20_foo_test",           (DL_FUNC) &_cpp20_foo_test,           0},
    {"_cpp20_foo_unique",         (DL_FUNC) &_cpp20_foo_unique,         1},
    {"_cpp20_foo_var",            (DL_FUNC) &_cpp20_foo_var,            2},
    {"_cpp20_foo_vec_add",        (DL_FUNC) &_cpp20_foo_vec_add,        2},
    {"_cpp20_foo_vec_divide",     (DL_FUNC) &_cpp20_foo_vec_divide,     2},
    {"_cpp20_foo_vec_multiply",   (DL_FUNC) &_cpp20_foo_vec_multiply,   2},
    {"_cpp20_foo_vec_subtract",   (DL_FUNC) &_cpp20_foo_vec_subtract,   2},
    {"_cpp20_foo_which",          (DL_FUNC) &_cpp20_foo_which,          1},
    {"_cpp20_foo_which_inverted", (DL_FUNC) &_cpp20_foo_which_inverted, 1},
    {"_cpp20_foobar",             (DL_FUNC) &_cpp20_foobar,             1},
    {"_cpp20_foofoo",             (DL_FUNC) &_cpp20_foofoo,             0},
    {"_cpp20_foofoofoo",          (DL_FUNC) &_cpp20_foofoofoo,          0},
    {"_cpp20_test1",              (DL_FUNC) &_cpp20_test1,              0},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_cpp20(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
