// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// dummy.cpp
double sum(cpp11::doubles x);
extern "C" SEXP _cpp20_sum(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(sum(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cpp20_sum", (DL_FUNC) &_cpp20_sum, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_cpp20(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
