// Generated by cpp20: do not edit by hand
// clang-format off

#ifndef R_NO_REMAP
#define R_NO_REMAP
#endif


#include <cpp20/internal/declarations.hpp>
#include <cpp20/internal/dispatch.hpp>
#include <R_ext/Visibility.h>

// test.cpp
r_int foo(r_int x);
extern "C" SEXP _cpp20_foo(SEXP x) {
  BEGIN_CPP20
    return cpp20::unwrap(cpp20::as<cpp20::r_sexp>(foo(cpp20::as<std::decay_t<r_int>>(x))));
  END_CPP20
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cpp20_foo", (DL_FUNC) &_cpp20_foo, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_cpp20(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
