// Generated by cpp20: do not edit by hand
// clang-format off

#include "test.h"
#include <cpp20/internal/declarations.hpp>
#include <cpp20/internal/dispatch.hpp>
#include <R_ext/Visibility.h>

// test.cpp
void cpp_set_threads(int n);
extern "C" SEXP _cpp20_cpp_set_threads(SEXP n) {
  BEGIN_CPP20
    cpp_set_threads(cpp20::as<std::decay_t<int>>(n));
    return R_NilValue;
  END_CPP20
}
// test.cpp
int bar(int x);
extern "C" SEXP _cpp20_bar(SEXP x) {
  BEGIN_CPP20
    return cpp20::unwrap(cpp20::as<cpp20::r_sexp>(bar(cpp20::as<std::decay_t<int>>(x))));
  END_CPP20
}
// test.h

extern "C" SEXP _cpp20_foo(SEXP n) {
  BEGIN_CPP20
    return cpp20::internal::dispatch_template_impl(
    []<typename T>(SEXP n_internal...) -> decltype(cpp20::unwrap(cpp20::as<cpp20::r_sexp>(foo(cpp20::as<cpp11::decay_t<T>>(n_internal))))) {
        return cpp20::unwrap(cpp20::as<cpp20::r_sexp>(foo(cpp20::as<cpp11::decay_t<T>>(n_internal))));
    },
    n
  );
  END_CPP20
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cpp20_bar",             (DL_FUNC) &_cpp20_bar,             1},
    {"_cpp20_cpp_set_threads", (DL_FUNC) &_cpp20_cpp_set_threads, 1},
    {"_cpp20_foo",             (DL_FUNC) &_cpp20_foo,             1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_cpp20(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
