# Generated by cpp11: do not edit by hand

dummy <- function() {
  invisible(.Call(`_cpp20_dummy`))
}

cpp_set_threads <- function(n) {
  invisible(.Call(`_cpp20_cpp_set_threads`, n))
}

foo <- function(x) {
  .Call(`_cpp20_foo`, x)
}

bar <- function(x) {
  .Call(`_cpp20_bar`, x)
}

foobar <- function(x) {
  .Call(`_cpp20_foobar`, x)
}

foofoo <- function() {
  .Call(`_cpp20_foofoo`)
}

ok <- function() {
  .Call(`_cpp20_ok`)
}

yeah <- function(x) {
  .Call(`_cpp20_yeah`, x)
}

foo2 <- function() {
  .Call(`_cpp20_foo2`)
}

foo4 <- function(x) {
  .Call(`_cpp20_foo4`, x)
}

foo5 <- function(x) {
  .Call(`_cpp20_foo5`, x)
}

foo6 <- function(x) {
  .Call(`_cpp20_foo6`, x)
}

foo7 <- function(x) {
  .Call(`_cpp20_foo7`, x)
}

foo8 <- function() {
  .Call(`_cpp20_foo8`)
}

foo9 <- function() {
  .Call(`_cpp20_foo9`)
}

foo10 <- function(x) {
  .Call(`_cpp20_foo10`, x)
}

foo_attrs <- function(x) {
  .Call(`_cpp20_foo_attrs`, x)
}

foo12 <- function(x, attrs) {
  .Call(`_cpp20_foo12`, x, attrs)
}

foo13 <- function(x) {
  .Call(`_cpp20_foo13`, x)
}

foo14 <- function() {
  .Call(`_cpp20_foo14`)
}

foo15 <- function() {
  .Call(`_cpp20_foo15`)
}

foo16 <- function(x) {
  .Call(`_cpp20_foo16`, x)
}

foo17 <- function(x) {
  .Call(`_cpp20_foo17`, x)
}

foo18 <- function(x) {
  .Call(`_cpp20_foo18`, x)
}

foo20 <- function() {
  .Call(`_cpp20_foo20`)
}

foo21 <- function(n) {
  .Call(`_cpp20_foo21`, n)
}

foo22 <- function(cols) {
  .Call(`_cpp20_foo22`, cols)
}

foo23 <- function() {
  .Call(`_cpp20_foo23`)
}

foo24 <- function(cols) {
  .Call(`_cpp20_foo24`, cols)
}

foo25 <- function(cols, x) {
  .Call(`_cpp20_foo25`, cols, x)
}

foo26 <- function() {
  .Call(`_cpp20_foo26`)
}

foo27 <- function(cols) {
  .Call(`_cpp20_foo27`, cols)
}

foo28 <- function(x, y) {
  .Call(`_cpp20_foo28`, x, y)
}

foo28a <- function(x, y) {
  .Call(`_cpp20_foo28a`, x, y)
}

foo28b <- function(x, y) {
  .Call(`_cpp20_foo28b`, x, y)
}

foo29 <- function(x) {
  .Call(`_cpp20_foo29`, x)
}

foo30 <- function() {
  .Call(`_cpp20_foo30`)
}

foo31 <- function() {
  .Call(`_cpp20_foo31`)
}

foo32 <- function() {
  .Call(`_cpp20_foo32`)
}

foo33 <- function() {
  .Call(`_cpp20_foo33`)
}

foo34 <- function() {
  .Call(`_cpp20_foo34`)
}

foo35 <- function() {
  .Call(`_cpp20_foo35`)
}

foo36 <- function(n) {
  .Call(`_cpp20_foo36`, n)
}

foo_rep_len <- function(x, n) {
  .Call(`_cpp20_foo_rep_len`, x, n)
}

foo_sum <- function(x, na_rm) {
  .Call(`_cpp20_foo_sum`, x, na_rm)
}

foo_sum_int <- function(x, na_rm) {
  .Call(`_cpp20_foo_sum_int`, x, na_rm)
}

foo_range <- function(x, na_rm) {
  .Call(`_cpp20_foo_range`, x, na_rm)
}

foo_na_count <- function(x) {
  .Call(`_cpp20_foo_na_count`, x)
}

foo39 <- function(x, na_rm) {
  .Call(`_cpp20_foo39`, x, na_rm)
}

foo40 <- function(x, na_rm) {
  .Call(`_cpp20_foo40`, x, na_rm)
}

foo41 <- function(x) {
  .Call(`_cpp20_foo41`, x)
}

foo42 <- function(x) {
  .Call(`_cpp20_foo42`, x)
}

foo43 <- function(x) {
  .Call(`_cpp20_foo43`, x)
}

foo44 <- function(x) {
  .Call(`_cpp20_foo44`, x)
}

foo46 <- function() {
  .Call(`_cpp20_foo46`)
}

foo47 <- function(n) {
  .Call(`_cpp20_foo47`, n)
}

foo48 <- function(x) {
  .Call(`_cpp20_foo48`, x)
}

foo49 <- function(x, na_rm) {
  .Call(`_cpp20_foo49`, x, na_rm)
}

foo50 <- function(x, na_rm) {
  .Call(`_cpp20_foo50`, x, na_rm)
}

foo51 <- function(x) {
  .Call(`_cpp20_foo51`, x)
}

foo52 <- function() {
  .Call(`_cpp20_foo52`)
}

foo53 <- function() {
  .Call(`_cpp20_foo53`)
}

foo54 <- function(x) {
  .Call(`_cpp20_foo54`, x)
}

foo55 <- function(x, y) {
  .Call(`_cpp20_foo55`, x, y)
}

foo56 <- function(x, y) {
  .Call(`_cpp20_foo56`, x, y)
}

foo57 <- function(x, y) {
  .Call(`_cpp20_foo57`, x, y)
}

foo58 <- function(x) {
  .Call(`_cpp20_foo58`, x)
}

foo_make_list <- function() {
  .Call(`_cpp20_foo_make_list`)
}

foo_make_list2 <- function() {
  .Call(`_cpp20_foo_make_list2`)
}

foo_add1 <- function(x, y) {
  .Call(`_cpp20_foo_add1`, x, y)
}

foo_add <- function(x) {
  .Call(`_cpp20_foo_add`, x)
}

foo_vec_add <- function(x) {
  .Call(`_cpp20_foo_vec_add`, x)
}

foo_vec_add2 <- function(x) {
  .Call(`_cpp20_foo_vec_add2`, x)
}

foo_vec_add3 <- function(x) {
  .Call(`_cpp20_foo_vec_add3`, x)
}

foo_vec_add4 <- function(x, y) {
  .Call(`_cpp20_foo_vec_add4`, x, y)
}

foo_vec_add5 <- function(x, y) {
  .Call(`_cpp20_foo_vec_add5`, x, y)
}

foo_vec_add6 <- function(x, y) {
  .Call(`_cpp20_foo_vec_add6`, x, y)
}

foo_vec_add7 <- function(x) {
  .Call(`_cpp20_foo_vec_add7`, x)
}

foo_vec_mod <- function(x) {
  .Call(`_cpp20_foo_vec_mod`, x)
}

foo_vec_mod2 <- function(x) {
  .Call(`_cpp20_foo_vec_mod2`, x)
}

foo_vec_mod3 <- function(x) {
  .Call(`_cpp20_foo_vec_mod3`, x)
}

foo_vec_mod4 <- function(x) {
  .Call(`_cpp20_foo_vec_mod4`, x)
}

foo_vec_subtract <- function(x, y) {
  .Call(`_cpp20_foo_vec_subtract`, x, y)
}

foo_vec_multiply <- function(x, y) {
  .Call(`_cpp20_foo_vec_multiply`, x, y)
}

foo_vec_divide <- function(x, y) {
  .Call(`_cpp20_foo_vec_divide`, x, y)
}

foo59 <- function(x) {
  .Call(`_cpp20_foo59`, x)
}

foo_factor <- function(x) {
  .Call(`_cpp20_foo_factor`, x)
}

foo_factor2 <- function(x, levels) {
  .Call(`_cpp20_foo_factor2`, x, levels)
}

foo_factor3 <- function() {
  .Call(`_cpp20_foo_factor3`)
}

foo_test <- function() {
  .Call(`_cpp20_foo_test`)
}

foo_test2 <- function() {
  .Call(`_cpp20_foo_test2`)
}

foo_gcd <- function(x, na_rm) {
  .Call(`_cpp20_foo_gcd`, x, na_rm)
}

foo_lcm <- function(x, na_rm) {
  .Call(`_cpp20_foo_lcm`, x, na_rm)
}

foo_range2 <- function(x) {
  .Call(`_cpp20_foo_range2`, x)
}

foo_range3 <- function(x) {
  .Call(`_cpp20_foo_range3`, x)
}

foo_sset <- function(x, i) {
  .Call(`_cpp20_foo_sset`, x, i)
}

foo_lgl <- function() {
  .Call(`_cpp20_foo_lgl`)
}

foo_unique <- function(x) {
  .Call(`_cpp20_foo_unique`, x)
}

foo_unique2 <- function(x) {
  .Call(`_cpp20_foo_unique2`, x)
}

foo_unique_strs <- function(x) {
  .Call(`_cpp20_foo_unique_strs`, x)
}

foo_as_str <- function(x) {
  .Call(`_cpp20_foo_as_str`, x)
}

foo_match_unique <- function(x) {
  .Call(`_cpp20_foo_match_unique`, x)
}

foo_match <- function(x, table) {
  .Call(`_cpp20_foo_match`, x, table)
}

foo_all_whole <- function(x) {
  .Call(`_cpp20_foo_all_whole`, x)
}

foo_copy <- function(x) {
  .Call(`_cpp20_foo_copy`, x)
}

foo_copy2 <- function(x) {
  .Call(`_cpp20_foo_copy2`, x)
}

foo_new_int <- function(n) {
  .Call(`_cpp20_foo_new_int`, n)
}

foo_copy_constructor <- function(x) {
  .Call(`_cpp20_foo_copy_constructor`, x)
}

foo_group_id <- function(x) {
  .Call(`_cpp20_foo_group_id`, x)
}

foo_n_groups <- function(x) {
  .Call(`_cpp20_foo_n_groups`, x)
}

foo_groups_sorted <- function(x) {
  .Call(`_cpp20_foo_groups_sorted`, x)
}

foo_group_starts <- function(x, n_groups, sorted) {
  .Call(`_cpp20_foo_group_starts`, x, n_groups, sorted)
}

foo_remainder <- function() {
  .Call(`_cpp20_foo_remainder`)
}

foo_between <- function(x, lo, hi) {
  .Call(`_cpp20_foo_between`, x, lo, hi)
}

foo_make_vec_test <- function() {
  .Call(`_cpp20_foo_make_vec_test`)
}

foo_test3 <- function(x, y) {
  .Call(`_cpp20_foo_test3`, x, y)
}

foo_na_real <- function() {
  .Call(`_cpp20_foo_na_real`)
}

foofoofoo <- function() {
  .Call(`_cpp20_foofoofoo`)
}

foo_subset <- function(x, i) {
  .Call(`_cpp20_foo_subset`, x, i)
}

foo_subset2 <- function(x, i) {
  .Call(`_cpp20_foo_subset2`, x, i)
}

foo_subset3 <- function(x, i) {
  .Call(`_cpp20_foo_subset3`, x, i)
}

foo_which <- function(x) {
  .Call(`_cpp20_foo_which`, x)
}

foo_which_inverted <- function(x) {
  .Call(`_cpp20_foo_which_inverted`, x)
}
