# Generated by cpp20: do not edit by hand

cpp_set_threads <- function(n) {
  invisible(.Call(`_cpp20_cpp_set_threads`, n))
}

cpp_get_threads <- function() {
  .Call(`_cpp20_cpp_get_threads`)
}

foo <- function(x) {
  .Call(`_cpp20_foo`, x)
}

bar <- function(x) {
  .Call(`_cpp20_bar`, x)
}

foo_is_na <- function(x) {
  .Call(`_cpp20_foo_is_na`, x)
}

foofoo <- function() {
  .Call(`_cpp20_foofoo`)
}

foo6 <- function(x) {
  .Call(`_cpp20_foo6`, x)
}

foo7 <- function(x) {
  .Call(`_cpp20_foo7`, x)
}

foo9 <- function() {
  .Call(`_cpp20_foo9`)
}

foo_attrs <- function(x) {
  .Call(`_cpp20_foo_attrs`, x)
}

foo12 <- function(x, attrs) {
  .Call(`_cpp20_foo12`, x, attrs)
}

foo14 <- function() {
  .Call(`_cpp20_foo14`)
}

foo26 <- function() {
  .Call(`_cpp20_foo26`)
}

foo27 <- function(cols) {
  .Call(`_cpp20_foo27`, cols)
}

foo28a <- function(x, y) {
  .Call(`_cpp20_foo28a`, x, y)
}

foo28b <- function(x, y) {
  .Call(`_cpp20_foo28b`, x, y)
}

foo30 <- function() {
  .Call(`_cpp20_foo30`)
}

foo_rep_len <- function(x, n) {
  .Call(`_cpp20_foo_rep_len`, x, n)
}

foo_sum <- function(x, na_rm) {
  .Call(`_cpp20_foo_sum`, x, na_rm)
}

foo_mean <- function(x, na_rm) {
  .Call(`_cpp20_foo_mean`, x, na_rm)
}

foo_var <- function(x, na_rm) {
  .Call(`_cpp20_foo_var`, x, na_rm)
}

foo_sum_int <- function(x, na_rm) {
  .Call(`_cpp20_foo_sum_int`, x, na_rm)
}

foo_range <- function(x, na_rm) {
  .Call(`_cpp20_foo_range`, x, na_rm)
}

foo_na_count <- function(x) {
  .Call(`_cpp20_foo_na_count`, x)
}

foo39 <- function(x, na_rm) {
  .Call(`_cpp20_foo39`, x, na_rm)
}

foo40 <- function(x, na_rm) {
  .Call(`_cpp20_foo40`, x, na_rm)
}

foo41 <- function(x) {
  .Call(`_cpp20_foo41`, x)
}

foo42 <- function(x) {
  .Call(`_cpp20_foo42`, x)
}

foo43 <- function(x) {
  .Call(`_cpp20_foo43`, x)
}

foo44 <- function(x) {
  .Call(`_cpp20_foo44`, x)
}

foo48 <- function(x) {
  .Call(`_cpp20_foo48`, x)
}

foo49 <- function(x, na_rm) {
  .Call(`_cpp20_foo49`, x, na_rm)
}

foo50 <- function(x, na_rm) {
  .Call(`_cpp20_foo50`, x, na_rm)
}

foo54 <- function(x) {
  .Call(`_cpp20_foo54`, x)
}

foo_add1 <- function(x, y) {
  .Call(`_cpp20_foo_add1`, x, y)
}

foo_add <- function(x) {
  .Call(`_cpp20_foo_add`, x)
}

foo_vec_add <- function(x, y) {
  .Call(`_cpp20_foo_vec_add`, x, y)
}

foo_vec_subtract <- function(x, y) {
  .Call(`_cpp20_foo_vec_subtract`, x, y)
}

foo_vec_multiply <- function(x, y) {
  .Call(`_cpp20_foo_vec_multiply`, x, y)
}

foo_vec_divide <- function(x, y) {
  .Call(`_cpp20_foo_vec_divide`, x, y)
}

foo_factor <- function(x) {
  .Call(`_cpp20_foo_factor`, x)
}

foo_factor2 <- function(x, levels) {
  .Call(`_cpp20_foo_factor2`, x, levels)
}

foo_gcd <- function(x, na_rm) {
  .Call(`_cpp20_foo_gcd`, x, na_rm)
}

foo_lcm <- function(x, na_rm) {
  .Call(`_cpp20_foo_lcm`, x, na_rm)
}

foo_sset <- function(x, i) {
  .Call(`_cpp20_foo_sset`, x, i)
}

foo_lgl <- function() {
  .Call(`_cpp20_foo_lgl`)
}

foo_unique <- function(x) {
  .Call(`_cpp20_foo_unique`, x)
}

foo_sorted_unique <- function(x) {
  .Call(`_cpp20_foo_sorted_unique`, x)
}

foo_as_str <- function(x) {
  .Call(`_cpp20_foo_as_str`, x)
}

foo_match <- function(x, table) {
  .Call(`_cpp20_foo_match`, x, table)
}

foo_all_whole <- function(x) {
  .Call(`_cpp20_foo_all_whole`, x)
}

foo_copy <- function(x) {
  .Call(`_cpp20_foo_copy`, x)
}

foo_group_id <- function(x) {
  .Call(`_cpp20_foo_group_id`, x)
}

foo_n_groups <- function(x) {
  .Call(`_cpp20_foo_n_groups`, x)
}

foo_groups_sorted <- function(x) {
  .Call(`_cpp20_foo_groups_sorted`, x)
}

foo_group_starts <- function(x, n_groups, sorted) {
  .Call(`_cpp20_foo_group_starts`, x, n_groups, sorted)
}

foo_remainder <- function() {
  .Call(`_cpp20_foo_remainder`)
}

foo_between <- function(x, lo, hi) {
  .Call(`_cpp20_foo_between`, x, lo, hi)
}

foo_make_vec_test <- function() {
  .Call(`_cpp20_foo_make_vec_test`)
}

foofoofoo <- function() {
  .Call(`_cpp20_foofoofoo`)
}

foo_which <- function(x) {
  .Call(`_cpp20_foo_which`, x)
}

foo_which_inverted <- function(x) {
  .Call(`_cpp20_foo_which_inverted`, x)
}

foo_asint64 <- function(x) {
  .Call(`_cpp20_foo_asint64`, x)
}

foo_order <- function(x) {
  .Call(`_cpp20_foo_order`, x)
}

foo_stable_order <- function(x) {
  .Call(`_cpp20_foo_stable_order`, x)
}

foo_slow_order <- function(x) {
  .Call(`_cpp20_foo_slow_order`, x)
}

foo_group_id2 <- function(x) {
  .Call(`_cpp20_foo_group_id2`, x)
}

foo_sorted <- function(x) {
  .Call(`_cpp20_foo_sorted`, x)
}

test1 <- function() {
  invisible(.Call(`_cpp20_test1`))
}

foo_null <- function() {
  .Call(`_cpp20_foo_null`)
}

foo_str_vectors <- function(x) {
  .Call(`_cpp20_foo_str_vectors`, x)
}

foo_seqs <- function(sizes, from, by) {
  .Call(`_cpp20_foo_seqs`, sizes, from, by)
}

foo_seqs2 <- function(sizes, from, by) {
  .Call(`_cpp20_foo_seqs2`, sizes, from, by)
}

foo_test <- function() {
  .Call(`_cpp20_foo_test`)
}

foo_abs <- function(x) {
  .Call(`_cpp20_foo_abs`, x)
}
