# Generated by cpp20: do not edit by hand

cpp_set_threads <- function(n) {
  invisible(.Call(`_cpp20_cpp_set_threads`, n))
}

test1 <- function(n) {
  .Call(`_cpp20_test1`, n)
}

test2 <- function(x) {
  .Call(`_cpp20_test2`, x)
}

test3 <- function(x) {
  .Call(`_cpp20_test3`, x)
}

test4 <- function(x) {
  .Call(`_cpp20_test4`, x)
}

foo <- function(x) {
  .Call(`_cpp20_foo`, x)
}

foo2 <- function(x) {
  .Call(`_cpp20_foo2`, x)
}

bar <- function(x) {
  .Call(`_cpp20_bar`, x)
}

foobar <- function(x) {
  .Call(`_cpp20_foobar`, x)
}

foo3 <- function(x, y) {
  .Call(`_cpp20_foo3`, x, y)
}
