# Generated by cpp20: do not edit by hand

cpp_set_threads <- function(n) {
  invisible(.Call(`_cpp20_cpp_set_threads`, n))
}

bar <- function(x) {
  .Call(`_cpp20_bar`, x)
}

foo <- function(n) {
  .Call(`_cpp20_foo`, n)
}
